### ISSUE TITLE
add emhash

### ISSUE THREAD

**Issue by ktprime** [koeppl/hashbench#1]
can add my emhash to your test？
https://github.com/ktprime/emhash/blob/master/hash_table5.hpp
https://github.com/ktprime/emhash/blob/master/hash_table6.hpp

**Comment by koeppl** [comment]
I can, but is there a reason why it is No. 5 and No. 6? Doesn't it make more sense to have one representative hash map, which is put in a file like `emhashmap.hpp` ?

**Comment by ktprime** [comment]
thanks.
  no5 and no6 is some different for use case . you can choose any one if you like(no6 can set very high load factor 0.99 without much performance loss for insertion). I also collected many thirdpatry bench hash map code in my git https://github.com/ktprime/emhash/tree/master/bench
